### ISSUE TITLE
Fails for package with a versioneer error

### ISSUE THREAD

**Issue by TheChymera** [mgorny/gpep517#1]
This ebuild: https://ppb.chymera.eu/bfa55f.39.4.ebuild
Will fail with this log: https://ppb.chymera.eu/d04e27.txt

Removing the `DISTUTILS_USE_PEP517=setuptools` line makes it work again.
I talked to upstream and sadly can't get any feedback since I can't actually tell him which command we use for him to test locally, as our command is not vanilla Python, but:

```
gpep517 build-wheel --backend setuptools.build_meta --output-fd 3 --wheel-dir /var/tmp/portage/dev-vcs/dandi-cli-0.39.4/work/dandi-cli-0.39.4-python3_9/wheel
```
using this package.

@mgorny any ideas what could be wrong or what I could do to get the actual Python call behind the `gpep517` command?

**Comment by mgorny** [comment]
It's upstream bug, filed https://github.com/dandi/dandi-cli/pull/998 with a fix.

**Comment by mgorny** [comment]
For local context: upstream is appending the current directory to `sys.path` rather than prepending it, so if `versioneer` is installed in site-packages, it takes precedence over the same-named local file.

**Comment by TheChymera** [comment]
Thank you!
